/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminHotelsRouteImport } from './routes/_authenticated/admin/hotels'
import { Route as AuthenticatedAdminVersionIdRouteImport } from './routes/_authenticated/admin/$versionId'
import { Route as AuthenticatedMerchantHotelsIndexRouteImport } from './routes/_authenticated/merchant.hotels.index'
import { Route as AuthenticatedMerchantHotelsHotelIdRouteImport } from './routes/_authenticated/merchant.hotels.$hotelId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/(auth)/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHotelsRoute =
  AuthenticatedAdminHotelsRouteImport.update({
    id: '/hotels',
    path: '/hotels',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVersionIdRoute =
  AuthenticatedAdminVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMerchantHotelsIndexRoute =
  AuthenticatedMerchantHotelsIndexRouteImport.update({
    id: '/merchant/hotels/',
    path: '/merchant/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantHotelsHotelIdRoute =
  AuthenticatedMerchantHotelsHotelIdRouteImport.update({
    id: '/merchant/hotels/$hotelId',
    path: '/merchant/hotels/$hotelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/$versionId': typeof AuthenticatedAdminVersionIdRoute
  '/admin/hotels': typeof AuthenticatedAdminHotelsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/merchant/hotels/$hotelId': typeof AuthenticatedMerchantHotelsHotelIdRoute
  '/merchant/hotels/': typeof AuthenticatedMerchantHotelsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/$versionId': typeof AuthenticatedAdminVersionIdRoute
  '/admin/hotels': typeof AuthenticatedAdminHotelsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/merchant/hotels/$hotelId': typeof AuthenticatedMerchantHotelsHotelIdRoute
  '/merchant/hotels': typeof AuthenticatedMerchantHotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/$versionId': typeof AuthenticatedAdminVersionIdRoute
  '/_authenticated/admin/hotels': typeof AuthenticatedAdminHotelsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/merchant/hotels/$hotelId': typeof AuthenticatedMerchantHotelsHotelIdRoute
  '/_authenticated/merchant/hotels/': typeof AuthenticatedMerchantHotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forget-password'
    | '/login'
    | '/register'
    | '/admin/$versionId'
    | '/admin/hotels'
    | '/admin/reviews'
    | '/merchant/hotels/$hotelId'
    | '/merchant/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forget-password'
    | '/login'
    | '/register'
    | '/'
    | '/admin/$versionId'
    | '/admin/hotels'
    | '/admin/reviews'
    | '/merchant/hotels/$hotelId'
    | '/merchant/hotels'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/(auth)/forget-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/'
    | '/_authenticated/admin/$versionId'
    | '/_authenticated/admin/hotels'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/merchant/hotels/$hotelId'
    | '/_authenticated/merchant/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hotels': {
      id: '/_authenticated/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AuthenticatedAdminHotelsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/$versionId': {
      id: '/_authenticated/admin/$versionId'
      path: '/$versionId'
      fullPath: '/admin/$versionId'
      preLoaderRoute: typeof AuthenticatedAdminVersionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/merchant/hotels/': {
      id: '/_authenticated/merchant/hotels/'
      path: '/merchant/hotels'
      fullPath: '/merchant/hotels/'
      preLoaderRoute: typeof AuthenticatedMerchantHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/hotels/$hotelId': {
      id: '/_authenticated/merchant/hotels/$hotelId'
      path: '/merchant/hotels/$hotelId'
      fullPath: '/merchant/hotels/$hotelId'
      preLoaderRoute: typeof AuthenticatedMerchantHotelsHotelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminVersionIdRoute: typeof AuthenticatedAdminVersionIdRoute
  AuthenticatedAdminHotelsRoute: typeof AuthenticatedAdminHotelsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminVersionIdRoute: AuthenticatedAdminVersionIdRoute,
    AuthenticatedAdminHotelsRoute: AuthenticatedAdminHotelsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMerchantHotelsHotelIdRoute: typeof AuthenticatedMerchantHotelsHotelIdRoute
  AuthenticatedMerchantHotelsIndexRoute: typeof AuthenticatedMerchantHotelsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMerchantHotelsHotelIdRoute:
    AuthenticatedMerchantHotelsHotelIdRoute,
  AuthenticatedMerchantHotelsIndexRoute: AuthenticatedMerchantHotelsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgetPasswordRoute: authForgetPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
