/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAddressSearchRouteImport } from './routes/_authenticated/address-search'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedListRoomTypeRouteImport } from './routes/_authenticated/list.$roomType'
import { Route as AuthenticatedHotelHotelIdRouteImport } from './routes/_authenticated/hotel.$hotelId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressSearchRoute =
  AuthenticatedAddressSearchRouteImport.update({
    id: '/address-search',
    path: '/address-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListRoomTypeRoute =
  AuthenticatedListRoomTypeRouteImport.update({
    id: '/list/$roomType',
    path: '/list/$roomType',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelHotelIdRoute =
  AuthenticatedHotelHotelIdRouteImport.update({
    id: '/hotel/$hotelId',
    path: '/hotel/$hotelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/address-search': typeof AuthenticatedAddressSearchRoute
  '/hotel/$hotelId': typeof AuthenticatedHotelHotelIdRoute
  '/list/$roomType': typeof AuthenticatedListRoomTypeRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/address-search': typeof AuthenticatedAddressSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/hotel/$hotelId': typeof AuthenticatedHotelHotelIdRoute
  '/list/$roomType': typeof AuthenticatedListRoomTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/address-search': typeof AuthenticatedAddressSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/hotel/$hotelId': typeof AuthenticatedHotelHotelIdRoute
  '/_authenticated/list/$roomType': typeof AuthenticatedListRoomTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/address-search'
    | '/hotel/$hotelId'
    | '/list/$roomType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/address-search'
    | '/'
    | '/hotel/$hotelId'
    | '/list/$roomType'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/address-search'
    | '/_authenticated/'
    | '/_authenticated/hotel/$hotelId'
    | '/_authenticated/list/$roomType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/address-search': {
      id: '/_authenticated/address-search'
      path: '/address-search'
      fullPath: '/address-search'
      preLoaderRoute: typeof AuthenticatedAddressSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/list/$roomType': {
      id: '/_authenticated/list/$roomType'
      path: '/list/$roomType'
      fullPath: '/list/$roomType'
      preLoaderRoute: typeof AuthenticatedListRoomTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotel/$hotelId': {
      id: '/_authenticated/hotel/$hotelId'
      path: '/hotel/$hotelId'
      fullPath: '/hotel/$hotelId'
      preLoaderRoute: typeof AuthenticatedHotelHotelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressSearchRoute: typeof AuthenticatedAddressSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHotelHotelIdRoute: typeof AuthenticatedHotelHotelIdRoute
  AuthenticatedListRoomTypeRoute: typeof AuthenticatedListRoomTypeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressSearchRoute: AuthenticatedAddressSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHotelHotelIdRoute: AuthenticatedHotelHotelIdRoute,
  AuthenticatedListRoomTypeRoute: AuthenticatedListRoomTypeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
